### PR TITLE
[WIP] dockerized

### PR DESCRIPTION
**Pull request by marclundgren**

### CODE REVIEW

**Comment by nkasmanoff** [comment]
@marclundgren thank you this is awesome, hope it can make it easier for others to tinker with this as well. Anything you'd want me to review before changing it from a draft to read for review? I have an extra pi with none of the dependencies already installed, so I'm planning at some point to try installing this repo using this approach in the next week or so

**Comment by marclundgren** [comment]
@nkasmanoff i made a ton of progress on this last week. Am planning on eventually publishing this PR when im ready. stay tuned

**Comment by nkasmanoff** [comment]
@marclundgren hey! Long time, hope all is well. Any updates on this from your side? If not, I'm going to give this a try soon, but I think I'm just going to copy your code to a branch I make off the latest and credit you in the README. Not sure if there's an easier way for me to take over this branch to do it

**Comment by marclundgren** [comment]
Hi @nkasmanoff This is eventually on my list of things to do but i don't have any plans on coming back to it soon -  maybe by EOY haha. I'm happy hop on a call sometime with some thoughts I had

**Comment by nkasmanoff** [comment]
@marclundgren sounds good! I sent you an invitation on LinkedIn (or at least I think it was you) to figure out a time when.

**Comment by nkasmanoff** [comment]
@marclundgren hey I started to test this again, did a quick merge conflict adjustment but not sure if that will still work on your side, however when trying to run here, I received the following error:

```
Recreating pi-card_pi-card_1 ... error

ERROR: for pi-card_pi-card_1  Cannot start service pi-card: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python": executable file not found in $PATH: unknown

ERROR: for pi-card  Cannot start service pi-card: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

I was able to successfully build the container, but this happened during docker compose up.

**Comment by marclundgren** [comment]
Hey Noah, I've been working on a fix specifically for getting the ALSA package working. This python error is fixed on my branch but overall is not yet ready to merge.

**Comment by nkasmanoff** [comment]
@marclundgren if you're still interested I think I got this working on this PR: https://github.com/nkasmanoff/pi-card/pull/19

**Pull request closed without merging**
